name: 🚀 Feature Request
description: Propose a new region, webhook integration, or feature for Nike SNKRS Tracker
title: "[FEAT]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a feature idea for Nike SNKRS Tracker!
  - type: textarea
    id: problem
    attributes:
      label: Feature Motivation
      description: What challenge or enhancement does this feature address?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Detailed description of how the feature should work.
    validations:
      required: true
